version: "3.8"
services:
  spotify_app:
    container_name: spotify_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - spotify_app
    networks:
      - app_network
  soptify_nginx:
    container_name: soptify_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - spotify_app
    environment:
      NGINX_FPM_HOST: spotify_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  spotify:
    container_name: spotify
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
